global_options:
  build_web_compilers:ddc:
    options:
      emit-debug-symbols: true

targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/**.dart
        options:
          # compiler: dart2js
          dart2js_args:
            # - --verbose
            # - --disable-inlining
            # - --generate-code-with-compile-time-errors
            # - --enable-diagnostic-colors
            - --omit-implicit-checks
            - --lax-runtime-type-to-string
            - --trust-primitives
            # - --server-mode
            # - --no-source-maps
            # - --fast-startup
            # - --minify